$schema: "http://json-schema.org/draft-07/schema#"
description: an entry in the sample sheet
properties:
  samplesheet:
    type: string
    description: sample name/identifier

  get_genome:
    properties:
      ncbi_ftp:
        type: string

  simulate_reads:
    properties:
      read_length:
        type: number
      read_number:
        type: number
      random_reads:
        type: number

required: ["samplesheet", "get_genome", "simulate_reads"]
